### ISSUE TITLE
Creating orders

### ISSUE THREAD

**Issue by ghost** [IlanFrumer/BitMEX-nodejs#2]
Can you create and close orders with this? Just want to make sure before I dive deep into this :)
If so, is there any example? I see that you mention that this module is capable of executing functions in the Bitmex API explorer ([https://www.bitmex.com/api/explorer/](https://www.bitmex.com/api/explorer/)).

**Comment by IlanFrumer** [comment]
https://www.bitmex.com/api/explorer/#!/Order/Order_new

examples

```typescript
const api = new BitmexAPI(config);
await api.Order.new({
    symbol: 'XBTUSD',
    side: 'Buy',
    orderQty: 10000,
    ordType: 'Market'
});

await api.Order.new({
    symbol: 'XBTUSD',
    side: 'Buy',
    orderQty: 10000,
    price: 3000,
    ordType: 'Limit'
});
```

**Comment by ghost** [comment]
Awesome! Wasn't sure what syntax to use, but now I see I can look at the URL for a pretty good idea o whats going on!
