### ISSUE TITLE
Socket is closing

### ISSUE THREAD

**Issue by JustDoItSascha** [IlanFrumer/BitMEX-nodejs#8]
Hey! First of all: Thanks for this client!

I use the BitmexSocket class and sometimes (like every 12-24h) the subscriptions are closing without an error and without being completed. They just stop emitting values...

Do you have any idea why this happens? I think this is a common issue, isn't it?

**Comment by DakotaLarson** [comment]
This is addressed here: https://github.com/IlanFrumer/BitMEX-nodejs/pull/12
